
package cursojava.Exceptions;

/**
 *
 * @author Hidelgio Novela
 */
public class Main2 {
    public static void main(String[] args) {
        
//        try and catch block

    try{
        int a = 5 / 0;
        
    }catch(Exception e){
        System.out.println("");
    }
    }
    
}
